--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/PMEssentials
build-by-default: true
branches:
- stable
projects:
  PMEssentials:
    path: ""
    icon: "assets/images/icon.png"
    lint:
      phpstan: false
...
